import { Inter } from "next/font/google";

import "./globals.css";
import Footer from "./components/layout/Footer/page";
import Header from "./components/layout/Header/page";
import { AdsProvider } from "./context/AdsContext";

import type { Metadata } from "next";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${interSans.variable} antialiased`}>
        <AdsProvider initialValue="full">
          <Header />
          {children}
          <Footer />
        </AdsProvider>
      </body>
    </html>
  );
}
